# Generated by Django 5.0 on 2023-12-23 11:53

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='dataOfJoining',
        ),
        migrations.AddField(
            model_name='employee',
            name='dateOfJoining',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
