# Generated by Django 5.0 on 2023-12-23 12:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_employee_phonenumber'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='unique_id',
        ),
    ]
