# Generated by Django 5.0 on 2023-12-23 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_remove_employee_unique_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='fingerprint_template',
            field=models.BinaryField(blank=True, null=True),
        ),
    ]
