# Generated by Django 5.0 on 2023-12-23 12:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_employee_fingerprint_template'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employee',
            old_name='fingerprint_template',
            new_name='fingerprint',
        ),
    ]
